services:
  c2_flask:
    build:
    context: app
    dockerfile: ./server/c2-dockerfile
  container_name: c2server
  image: digitalocean.com/flask-python:3.10
  restart: unless-stopped
  environment:
    APP_ENV: "development"
    APP_DEBUG: "True"
    APP_PORT: 5000
    MONGODB_DATABASE: resultsdb
    MONGODB_USERNAME: hackiador
    MONGODB_PASSWORD: muy_seguro
    MONGODB_HOSTNAME: mongodb
  volumes:
    - appdata:/var/www
  depends_on:
    - mongodb
  networks:
    - frontend
    - backend

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME: hackiador
      - MONGO_INITDB_ROOT_PASSWORD: muy_seguro
      - MONGO_INITDB_DATABASE: resultsdb
      - MONGODB_DATA_DIR: /data/db
      - MONGODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
    ports:
      - 27017:27017
