# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Box
  config.vm.box = "StefanScherer/windows_2019"

  # Additional parameters to communicate with Windows
  config.vm.boot_timeout = 60
  config.vm.communicator = "winrm"
  config.winrm.port = 55985

  # Customization
  config.vm.provider "virtualbox" do |v|
    v.name = "my_vms"
    v.gui = true
    v.memory = 1024
    v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"] # Enables drag-and-drop between host and guest
  end
  config.vm.network :forwarded_port, guest: 80, host: 8080, id: "http"

  # Provisioning
  config.vm.provision "shell", path: "scripts/InstallChocolatey.ps1"
  config.vm.provision "shell", inline: "choco install vscode --yes"
  config.vm.provision "shell", inline: "choco install vcredist-all --yes"
  config.vm.provision "shell", inline: "choco install boost-msvc-14.3 --yes"
  config.vm.provision "shell", inline: "choco install git.portable"

end